name = "TidyStanza"
uuid = "b2c96470-cb50-47b8-9d8d-45534fe4e5bb"
authors = ["Dai ZJ <zhuojia.dai@gmail.com> and contributors"]
version = "0.1.5"

[deps]
DataConvenience = "3b531cbf-ee43-4e67-8118-dca2c9372f86"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataConvenience = "0.1, 0.2, 0.3"
DataFrames = "1"
julia = "1"

[extras]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Chain"]
